---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [--strict, -c=.yamllint]

  - repo: local
    hooks:
      - id: dprint
        name: dprint fmt
        entry: dprint fmt
        args: ["--allow-no-files"]
        language: node
        additional_dependencies: ["dprint@0.55.1"]
