---
name: pre-commit

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: okhiroyuki/composite-actions
          path: ./.github/actions/composite-actions
      - uses: ./.github/actions/composite-actions/setup-node
      - uses: ./.github/actions/composite-actions/pre-commit
